env:
  matrix:
    secure: FLBGA7zDxOO9p0zyxI5kcHxtCFX0hxwNq1kO0GLSQLuovj9b007aguaI2UhBkCBPlwJ9m8/yhr2Vf+dpCUn7ka7ro5A0qRhhPfs3eTb+qITINMlKOkZNsMI5fuYvwemhPXPDgDjumUsYWuCgj9IiJ9L9DS6Q9WmmyM5qpFTFNSfLmRHwJ9R4einF8Y0V+u2+QgqGSybuSAaokfXz4BUsRTuHpPD50s/0BFORG3+BxQqUcI1JymmygZG9T+3a8087DcVRJw2+536oVa/vRKsKRVQkayI8/Jgy/Qo70vRLB8zACruIg/PNFwtA0hbqB3KfS2FX+s9xah7a/BqTpSYRCbvmGGJFE6u2KpLRmM+Tuderu0h61wjOFZzGJiiFsN6U2SDV3UtDh382K8MLQMyQB9leKBNv3wUFH9x+jsaN5GshEZR1jp6jZgjCp4tR7COMjzXN+8qzMOvb/urqnNr23Ld+M+17YhefKZ9UH1nkgSXheeOjVLp580Yi/hFpuKdCI4KEy5ClWG/4wDoJxwli177JnQ3P9JzAUcjwLvBNSLmmB+FU3q0qCIUnAQUOzC8+752R5wTgmAZngYI89nf2+yOpV8gX9RvolgmvfJbFTBIYorbLhpI8wGeRqk8HgNi4yf/8GwsrjFIOAAaJKjxBGRSxfbDzPBbUBWhg0G5QPlM=
language: java
addons:
  sonarcloud:
    organization: pascalpoizat-github
    token:
      secure: lLGKQ2J6N9POJVl7yTOHwwggozOwH0V3gQN4yjKnJVH8pY5fvGh8552K4vECDJc+d1ZH9nVa3mRcFwLSKanuhpnyNXm6foy4EvBHcbwx6FJihDutMmiYqlwE92eAIU4OcdbnG38MGMzO2pRw+ZxFRz8uU/EOMW6T9ABS//FZ9rGTye25akHPDFRpHeGEtfdU0QGYbCgUo5OK/146HdXNfriIVlbuuUKAM17CPkx9b5oMcN9TYgWb18fzpnpU6eDzqeB1suDf1VSbFLYrKvvm7yjKyU6BWFFFLeeWj0OxzKOJ6texlC2Otn5E2nIY89q1y2dHbIiTwXNVPnTXRwMliLmP+xt6GEAjKCtyOgSerK6DdXC2n6t6XYyYerZbb6p7P7IEts8/zJOIsufoLP4mWXWgipZyNEAyWNpJTVsjYfUe3yks+MRsq8Ma7pO87DDyj7WQYjvbQ4hX0O5hZcM01hdpMxk7TpMh607RRLx6kcMr76ELab4l1iDGNyXIG+l776hFuWmuXBDRd1ogFwdGMU+BsH/CP4sLG/hMwAqSzlJIlttBektcOKzFPTyf9Megh8xv2ZxaKQNxSor0bdHUP1rN/bmubss2fBiPauTti8HGHb5DO6IhBjmysXdcISIyTpQ53JEYaO84L2TBdy4JibHk6LX1uAVQ+mfftt39sLs=
sudo: false
before_install:
- sudo apt-get -y install graphviz
script:
- "./gradlew check jacocoTestReport coveralls sendCoverageToCodacy"
- bash <(curl -s https://codecov.io/bash)
- "./gradlew sonarqube"
after_success:
- "./gradlew jar"
- "./gradlew asciidoctor"
before_deploy:
- export VERSION=`./gradlew -q version`
- export BINDIR="build/libs"
- export BINFILE="template-java-project-${VERSION}"
- export DOCDIR="build/docs/asciidocPdf"
- export DOCFILE="main"
- mv "${DOCDIR}/${DOCFILE}.pdf" "${DOCDIR}/${DOCFILE}-${VERSION}.pdf"
- export BINARY="${BINDIR}/${BINFILE}.jar"
- export DOCUMENTATION="${DOCDIR}/${DOCFILE}-${VERSION}.pdf"
- echo binary is ${BINARY}
- echo documentation is ${DOCUMENTATION}
- |
  if [ $TRAVIS_BRANCH = "develop" ]
  then
    export TRAVIS_TAG=v${VERSION}-SNAPSHOT
  else
    export TRAVIS_TAG=v${VERSION}
  fi
- |
  if [ $TRAVIS_BRANCH = "develop" ]
  then
    git tag ${TRAVIS_TAG}
    echo tag ${TRAVIS_TAG}
  else
    echo no tag
  fi

deploy:
  - provider: releases
    api_key:
      secure: MnEsOM7EBcWyaPrHXfIJ4+RLMOezxdM8/PqgK3KBBFD9/YDlNITgoAEkCeZDSF0KkgyrvuyPzJXYsj/jUxzMYp7NjxrVwovyTjJu017Bzz5eAuaZpM0OLF/IYlJJuXCaBSYQeGaNlo16l18JhSX5dMC+RF402PxVdyfp4VvpXZ0mo3n9BcbJGy5BFj/pZkssPqmVKCzc2c5dKmOk861Y4ckX0/KlC35S1YolGV1jD4ceZk5qFMU/MKeTkqNMtSbz0bqBxWvR5xdQg3Ri590H32z8vMu1NTKtyLVAoTbEO1dVeiO6MqwMTiJLyN7Nma55yMhiBSYpsmT/9dletVXVl1GfK+gpzs6RE5AOQB+m8g805/XMqrPv5XonOoJ1RleHkPpnNt0kFeb3piCB0hejeVvGkfUvgNfL3LzgcvelMFE2KZ7Zr2EjfyanV24SA2g1VufCvKirlXKiblY3jFxzTAZE8RVPrlIWDtncVmV8IAza/RzCPEOF9t2cSN2o90b2XNr6NfhPVAmXRCw9Wvks602Z1jLSuluyOeVhvKqrdZToKu3lhRGaTkRpJDu9QE4JATrhLQ+gddXkllzU9FUQn2Rdk8TokgS5SYnSef4SX3tIQ7MXvvhQDg+uCOF/wMJecN/hqHX/YDG7Mucix8MGQoU+0wLLRPAj/3KHO2rMcZQ=
    file:
      - ${BINARY}
      - ${DOCUMENTATION}
    skip_cleanup: true
    overwrite: true
    draft: false
    on:
      #branch master
      tags: true
      all_branches: true
    name: $TRAVIS_TAG
  - provider: releases
    api_key:
      secure: MnEsOM7EBcWyaPrHXfIJ4+RLMOezxdM8/PqgK3KBBFD9/YDlNITgoAEkCeZDSF0KkgyrvuyPzJXYsj/jUxzMYp7NjxrVwovyTjJu017Bzz5eAuaZpM0OLF/IYlJJuXCaBSYQeGaNlo16l18JhSX5dMC+RF402PxVdyfp4VvpXZ0mo3n9BcbJGy5BFj/pZkssPqmVKCzc2c5dKmOk861Y4ckX0/KlC35S1YolGV1jD4ceZk5qFMU/MKeTkqNMtSbz0bqBxWvR5xdQg3Ri590H32z8vMu1NTKtyLVAoTbEO1dVeiO6MqwMTiJLyN7Nma55yMhiBSYpsmT/9dletVXVl1GfK+gpzs6RE5AOQB+m8g805/XMqrPv5XonOoJ1RleHkPpnNt0kFeb3piCB0hejeVvGkfUvgNfL3LzgcvelMFE2KZ7Zr2EjfyanV24SA2g1VufCvKirlXKiblY3jFxzTAZE8RVPrlIWDtncVmV8IAza/RzCPEOF9t2cSN2o90b2XNr6NfhPVAmXRCw9Wvks602Z1jLSuluyOeVhvKqrdZToKu3lhRGaTkRpJDu9QE4JATrhLQ+gddXkllzU9FUQn2Rdk8TokgS5SYnSef4SX3tIQ7MXvvhQDg+uCOF/wMJecN/hqHX/YDG7Mucix8MGQoU+0wLLRPAj/3KHO2rMcZQ=
    file:
      - ${BINARY}
      - ${DOCUMENTATION}
    skip_cleanup: true
    overwrite: true
    draft: true
    on:
      branch: develop
      tags: false
    name: $TRAVIS_TAG

cache:
  directories:
    - "$HOME/.sonar/cache"    